dependencies:
- condition: activiti-cloud-query.enabled
  name: activiti-cloud-query
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.7
- condition: activiti-cloud-audit.enabled
  name: activiti-cloud-audit
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.6
- alias: rabbitmq
  condition: rabbitmq.enabled
  name: rabbitmq-ha
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.6.0