appVersion: 3.4.3.Final
description: Open Source Identity and Access Management For Modern Applications and
  Services
home: http://www.keycloak.org/
icon: http://www.keycloak.org/resources/images/keycloak_logo_480x108.png
keywords:
- authentication
maintainers:
- email: marcel@beck.im
  name: nexeck
- email: unguiculus@gmail.com
  name: unguiculus
name: keycloak
sources:
- https://github.com/jboss-dockerfiles/keycloak
version: 1.0.1
