apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jx-staging-quickstart-http.jx-staging.activiti.envalfresco.com
    http:
      paths:
      - path: /rb-my-app
        backend:
          serviceName: {{ .Release.Name }}-example-runtime-bundle
          servicePort: 80
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-keycloak-http
          servicePort: 80
      - path: /rabbitmq
        backend:
          serviceName: {{ .Release.Name }}-rabbitmq
          servicePort: 15672
      - path: /query
        backend:
          serviceName: {{ .Release.Name }}-activiti-cloud-query
          servicePort: 80