dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: example-runtime-bundle
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.27
- name: infrastructure
  repository: file://../infrastructure
  version: 0.1.0
- name: application
  repository: file://../application
  version: 0.1.0
- name: activiti-cloud-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.23
