dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: rabbitmq
  name: rabbitmq-ha
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.6.0
  condition: rabbitmq.enabled
- name: example-runtime-bundle
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.19
- alias: activitipostgresql
  name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.11.0
- name: keycloak
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 2.0.0
  condition: keycloak.enabled
- alias: querypostgresql
  name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.11.0
  condition: activiti-cloud-query.enabled
- name: activiti-cloud-query
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.3
  condition: activiti-cloud-query.enabled
- name: activiti-cloud-audit
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.1
  condition: activiti-cloud-audit.enabled
