dependencies:
- name: activiti-cloud-connector-slack
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- alias: activiti-cloud
  name: activiti-cloud-full-example
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.3.0
- name: activiti-cloud-rb-create-article
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.69
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.69
