expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: activiti.envalfresco.com
    exposer: Ingress
    http: "true"
    tlsacme: "false"
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

global:
  keycloak:
    url: "http://jx-staging-quickstart-http.jx-staging.activiti.envalfresco.com/auth"

activiti-cloud-demo-ui:
  service:
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.name: activiti
      fabric8.io/ingress.path: /ui/
      fabric8.io/ingress.annotations: |-
        kubernetes.io/ingress.class: nginx
  gatewayUrl:  "http://activiti-cloud-gateway.jx-staging.activiti.envalfresco.com"
  idmUrl: "http://jx-staging-quickstart-http.jx-staging.activiti.envalfresco.com/auth/realms/activiti/protocol/openid-connect/token"
  idmClientId:  "activiti"

application:
  activiti-cloud-query:
    db:
      name: querypostgresql
      password: query
  querypostgresql:
     postgresPassword: query
  activiti-cloud-demo-ui:
    enabled: false

infrastructure:
  activiti-keycloak:
    keycloak:
      enabled: true
      keycloak:
        username: admin
        password: admin
        persistence:
          deployPostgres: false
          dbVendor: H2
        ingress:
          enabled: false
        extraEnv: |
         - name: PROXY_ADDRESS_FORWARDING
           value: "true"
         - name: EXPOSE_URL
           valueFrom:
             configMapKeyRef:
               name: {{ .Release.Name }}-keycloak-http
               key: expose-keycloak-service-key
         - name: HOST_KEY
           valueFrom:
             configMapKeyRef:
               name: {{ .Release.Name }}-keycloak-http
               key: host-key
        service:
          annotations:
            fabric8.io/expose: "true"
            fabric8.io/ingress.name: activiti
            fabric8.io/ingress.annotations: |-
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/cors-allow-headers: X-Forwarded-For,X-Forwarded-Proto,X-Forwarded-Port,X-Forwarded-Prefix,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-CSRF-Token,Access-Control-Request-Headers,Access-Control-Request-Method,accept,Keep-Alive
              nginx.ingress.kubernetes.io/enable-cors: true
              nginx.ingress.kubernetes.io/x-forwarded-prefix: true
            fabric8.io/ingress.path: /auth/
        preStartScript: |
          cp /realm/activiti-realm.json .
          sed -i "s/activiti-cloud-demo-ui:30082/$HOST_KEY\/ui/g" activiti-realm.json
          sed -i "s/activiti-cloud-demo-ui:\*/$HOST_KEY:*/g" activiti-realm.json
  activiti-cloud-gateway:
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.name: activiti
        kubernetes.io/ingress.class: nginx
        fabric8.io/ingress.annotations: |-
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/enable-cors: true
          nginx.ingress.kubernetes.io/cors-allow-headers: "*"
          nginx.ingress.kubernetes.io/x-forwarded-prefix: true