expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: activiti.envalfresco.com
    exposer: Ingress
    http: "true"
    tlsacme: "false"
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

rabbitmq:
  rabbitmq:
    username: "guest"
    password: "guest"
  ingress:
    enabled: true
activitipostgresql:
   postgresPassword: activiti
keycloak:
  keycloak:
    username: admin
    password: admin
    persistence:
      deployPostgres: false
      dbVendor: H2
    ingress:
      enabled: true
      hosts:
       - "jx-staging-example-keycloak-http.jx-staging.activiti.envalfresco.com"
    livenessProbe:
      initialDelaySeconds: 140
    extraVolumes: |
      - name: realm-secret
        secret:
          secretName: {{ .Release.Name }}-realm-secret
    extraVolumeMounts: |
      - name: realm-secret
        mountPath: "/realm/"
        readOnly: true
    extraArgs: -Dkeycloak.import=/realm/activiti-realm.json
example-runtime-bundle:
  db:
    name: activitipostgresql

global:
  keycloak:
    url: "http://jx-staging-example-keycloak-http.jx-staging.activiti.envalfresco.com/auth"